name: fluquery
description: >-
  Powerful asynchronous state management, server-state utilities and data fetching 
  for Flutter. Inspired by TanStack Query (React Query). Features automatic caching, 
  background refetching, mutations, infinite queries, and optimistic updates.
version: 1.0.2
homepage: https://github.com/Ashkan-Oliaie/FluQuery
repository: https://github.com/Ashkan-Oliaie/FluQuery
issue_tracker: https://github.com/Ashkan-Oliaie/FluQuery/issues
documentation: https://github.com/Ashkan-Oliaie/FluQuery#readme

topics:
  - state-management
  - caching
  - api
  - hooks
  - query

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  collection: ^1.18.0
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
